### ISSUE TITLE
Fix periodic database errors

### ISSUE THREAD

**Issue by kochman** [wtg/elections#93]
Every few minutes, the server gets an error from the mysql connection. I added some logging in dfbcd07 to try to figure this out. I only see this on the server; I can't reproduce locally.

```
2018-03-04T17:42:15.987011395Z app[web.1]: 2018-03-04T17:42:15.986Z elections:database Error: Connection lost: The server closed the connection.
2018-03-04T17:42:15.987088706Z app[web.1]:     at Protocol.end (/app/node_modules/mysql/lib/protocol/Protocol.js:113:13)
2018-03-04T17:42:15.987113449Z app[web.1]:     at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:109:28)
2018-03-04T17:42:15.987133980Z app[web.1]:     at emitNone (events.js:111:20)
2018-03-04T17:42:15.987154006Z app[web.1]:     at Socket.emit (events.js:208:7)
2018-03-04T17:42:15.987172617Z app[web.1]:     at endReadableNT (_stream_readable.js:1055:12)
2018-03-04T17:42:15.987190703Z app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
2018-03-04T17:42:15.987211264Z app[web.1]:     at process._tickCallback (internal/process/next_tick.js:180:9)
2018-03-04T17:43:23.538900412Z app[web.1]: 2018-03-04T17:43:23.538Z elections:database Error: Connection lost: The server closed the connection.
2018-03-04T17:43:23.539201198Z app[web.1]:     at Protocol.end (/app/node_modules/mysql/lib/protocol/Protocol.js:113:13)
2018-03-04T17:43:23.539330842Z app[web.1]:     at Socket.<anonymous> (/app/node_modules/mysql/lib/Connection.js:109:28)
2018-03-04T17:43:23.539360836Z app[web.1]:     at emitNone (events.js:111:20)
2018-03-04T17:43:23.539380330Z app[web.1]:     at Socket.emit (events.js:208:7)
2018-03-04T17:43:23.539495284Z app[web.1]:     at endReadableNT (_stream_readable.js:1055:12)
2018-03-04T17:43:23.540101059Z app[web.1]:     at _combinedTickCallback (internal/process/next_tick.js:138:11)
2018-03-04T17:43:23.540131146Z app[web.1]:     at process._tickCallback (internal/process/next_tick.js:180:9)
```

I think we may want to move to a connection pool.

**Comment by kochman** [comment]
So I think 289773a fixes this. The candidate by RCS route never closed its database connection, and it gets hit whenever anyone visits the home page or a candidate page. Eventually the connections time out (after 10 min according to the server's MariaDB config) resulting in that connection error. Will continue to monitor.
